version: "3.0"
services:
    core:
        image: elabosak233/cloudsdale:main
        restart: always
        ports:
            - "8888:8888"
        volumes:
            - "./application.toml:/app/application.toml:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./assets:/app/assets"
            - "./captures:/app/captures"
            - "./media:/app/media"
            - "./logs:/app/logs"
        depends_on:
            - db
            - queue
            - cache

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: cloudsdale
            POSTGRES_PASSWORD: cloudsdale
            POSTGRES_DB: cloudsdale
        volumes:
            - "./db:/var/lib/postgresql/data"

    queue:
        image: nats:alpine
        restart: always
        command:
            - "--js"
            - "--sd=/data"
        volumes:
            - "./queue:/data"

    cache:
        image: redis:alpine
        restart: always
        volumes:
            - "./cache:/data"
