name: Docker Build & Push

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: elabosak233/cloudsdale
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Ghcr Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: elabosak233
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: elabosak233
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/cloudsdale
            docker.io/${{ github.repository_owner }}/cloudsdale
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
